version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      zk_id: "1"
    networks:
      - confluent

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - confluent

  producers:
    image: rbcvlr/villo_producers
  #  build:
  #    context: ./producer
  #    dockerfile: ./Dockerfile
    networks:
      - confluent
    depends_on:
      - kafka
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    networks:
      - confluent

  ksql-server:
    image: confluentinc/cp-ksql-cli
    depends_on:
      - kafka
      - schema-registry
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      - confluent

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    command: logstash -f /config/logstash.conf
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - $PWD/logstash/config:/config
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - confluent

  elasticsearch:
    image: elasticsearch:6.4.2
    hostname: elasticsearch
    volumes:
      - /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - confluent
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false

  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - logstash
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - confluent

networks:
  confluent:
    driver: "bridge"
